### ISSUE TITLE
policy module error

### ISSUE THREAD

**Issue by kevingstewart** [kevingstewart/f5_sslo_ansible#8]
Reported by J Lee.

Issue: following error message attempting to create a security policy

```
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_bigip_sslo_config_policy_payload_urrcjety/ansible_bigip_sslo_config_policy_payload.zip/ansible_collections/kevingstewart/f5_sslo_ansible/plugins/modules/bigip_sslo_config_policy.py", line 1084, in ssloGS_global_exists
IndexError: list index out of range
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "/home/ubuntu/.ansible/tmp/ansible-tmp-1631810720.7616959-24546-53242799437317/AnsiballZ_bigip_sslo_config_policy.py", line 100, in <module>
    _ansiballz_main()
  File "/home/ubuntu/.ansible/tmp/ansible-tmp-1631810720.7616959-24546-53242799437317/AnsiballZ_bigip_sslo_config_policy.py", line 92, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/ubuntu/.ansible/tmp/ansible-tmp-1631810720.7616959-24546-53242799437317/AnsiballZ_bigip_sslo_config_policy.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.kevingstewart.f5_sslo_ansible.plugins.modules.bigip_sslo_config_policy', init_globals=dict(_module_fqn='ansible_collections.kevingstewart.f5_sslo_ansible.plugins.modules.bigip_sslo_config_policy', _modlib_path=modlib_path),
  File "/usr/lib/python3.8/runpy.py", line 207, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_bigip_sslo_config_policy_payload_urrcjety/ansible_bigip_sslo_config_policy_payload.zip/ansible_collections/kevingstewart/f5_sslo_ansible/plugins/modules/bigip_sslo_config_policy.py", line 2496, in <module>
  File "/tmp/ansible_bigip_sslo_config_policy_payload_urrcjety/ansible_bigip_sslo_config_policy_payload.zip/ansible_collections/kevingstewart/f5_sslo_ansible/plugins/modules/bigip_sslo_config_policy.py", line 2485, in main
  File "/tmp/ansible_bigip_sslo_config_policy_payload_urrcjety/ansible_bigip_sslo_config_policy_payload.zip/ansible_collections/kevingstewart/f5_sslo_ansible/plugins/modules/bigip_sslo_config_policy.py", line 2211, in exec_module
  File "/tmp/ansible_bigip_sslo_config_policy_payload_urrcjety/ansible_bigip_sslo_config_policy_payload.zip/ansible_collections/kevingstewart/f5_sslo_ansible/plugins/modules/bigip_sslo_config_policy.py", line 2228, in update
  File "/tmp/ansible_bigip_sslo_config_policy_payload_urrcjety/ansible_bigip_sslo_config_policy_payload.zip/ansible_collections/kevingstewart/f5_sslo_ansible/plugins/modules/bigip_sslo_config_policy.py", line 2143, in update_json
  File "/tmp/ansible_bigip_sslo_config_policy_payload_urrcjety/ansible_bigip_sslo_config_policy_payload.zip/ansible_collections/kevingstewart/f5_sslo_ansible/plugins/modules/bigip_sslo_config_policy.py", line 1103, in ssloGS_global_exists
KeyError: 'version'
fatal: [localhost -> localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_bigip_sslo_config_policy_payload_urrcjety/ansible_bigip_sslo_config_policy_payload.zip/ansible_collections/kevingstewart/f5_sslo_ansible/plugins/modules/bigip_sslo_config_policy.py\", line 1084, in ssloGS_global_exists\nIndexError: list index out of range\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1631810720.7616959-24546-53242799437317/AnsiballZ_bigip_sslo_config_policy.py\", line 100, in <module>\n    _ansiballz_main()\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1631810720.7616959-24546-53242799437317/AnsiballZ_bigip_sslo_config_policy.py\", line 92, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1631810720.7616959-24546-53242799437317/AnsiballZ_bigip_sslo_config_policy.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.kevingstewart.f5_sslo_ansible.plugins.modules.bigip_sslo_config_policy', init_globals=dict(_module_fqn='ansible_collections.kevingstewart.f5_sslo_ansible.plugins.modules.bigip_sslo_config_policy', _modlib_path=modlib_path),\n  File \"/usr/lib/python3.8/runpy.py\", line 207, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.8/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_bigip_sslo_config_policy_payload_urrcjety/ansible_bigip_sslo_config_policy_payload.zip/ansible_collections/kevingstewart/f5_sslo_ansible/plugins/modules/bigip_sslo_config_policy.py\", line 2496, in <module>\n  File \"/tmp/ansible_bigip_sslo_config_policy_payload_urrcjety/ansible_bigip_sslo_config_policy_payload.zip/ansible_collections/kevingstewart/f5_sslo_ansible/plugins/modules/bigip_sslo_config_policy.py\", line 2485, in main\n  File \"/tmp/ansible_bigip_sslo_config_policy_payload_urrcjety/ansible_bigip_sslo_config_policy_payload.zip/ansible_collections/kevingstewart/f5_sslo_ansible/plugins/modules/bigip_sslo_config_policy.py\", line 2211, in exec_module\n  File \"/tmp/ansible_bigip_sslo_config_policy_payload_urrcjety/ansible_bigip_sslo_config_policy_payload.zip/ansible_collections/kevingstewart/f5_sslo_ansible/plugins/modules/bigip_sslo_config_policy.py\", line 2228, in update\n  File \"/tmp/ansible_bigip_sslo_config_policy_payload_urrcjety/ansible_bigip_sslo_config_policy_payload.zip/ansible_collections/kevingstewart/f5_sslo_ansible/plugins/modules/bigip_sslo_config_policy.py\", line 2143, in update_json\n  File \"/tmp/ansible_bigip_sslo_config_policy_payload_urrcjety/ansible_bigip_sslo_config_policy_payload.zip/ansible_collections/kevingstewart/f5_sslo_ansible/plugins/modules/bigip_sslo_config_policy.py\", line 1103, in ssloGS_global_exists\nKeyError: 'version'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

**Comment by kevingstewart** [comment]
Resolved (17-September-2021). Issue was found in ssloGS_global_exists() function, not correctly handling a non-existent ssloGS_global config. Updated to properly handle this condition. Separate issue was a type in json "version" settings (line 1103-1105), was using "-" instead of "=" for assignment.
